name: Publish Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lyliiian
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          #platforms: linux/amd64,linux/arm64/v8
          platforms: linux/arm64
          push: true
          tags: lyliiian/catma-parser:latest
